name: Create Pull Request

on:
  push:
    branches:
      - dev

jobs: 
    CreatePullRequest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3.6.0
          with:
            delete-branch: 'false'
            draft: 'true'

