name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  createPullRequest:
    if: "!contains(github.event.head_commit.message, 'don't deploy')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: false
          title: '[Example] Update report'
          assignees: ramyaramdasan
          draft: true

